import type { Component } from 'svelte';
import * as kit from '$lib';

export const registry: Record<string, Component> = {
	Badge: kit.Badge,
	Callout: kit.Callout,
	Columns: kit.Columns,
	Kbd: kit.Kbd,
	Update: kit.Update,
	Roadmap: kit.Roadmap,
	RoadmapItem: kit.RoadmapItem,
	Card: kit.Card,
	CardGroup: kit.CardGroup,
	CodeGroup: kit.CodeGroup,
	Accordion: kit.Accordion,
	AccordionGroup: kit.AccordionGroup,
	Tabs: kit.Tabs,
	Tab: kit.Tab,
	Steps: kit.Steps,
	Step: kit.Step,
	Frame: kit.Frame,
	Icon: kit.Icon,
	Tooltip: kit.Tooltip,
	Tree: kit.Tree,
	Video: kit.Video,
	Folder: kit.Folder,
	File: kit.File,
	TypeTable: kit.TypeTable,
	Webhook: kit.Webhook,
	EventList: kit.EventList,
	Event: kit.Event,
	Channel: kit.Channel,
	Message: kit.Message,
	Api: kit.Api,
	Endpoint: kit.Endpoint,
	ParamField: kit.ParamField,
	ResponseField: kit.ResponseField,
	RequestExample: kit.RequestExample,
	ResponseExample: kit.ResponseExample,
	ObjectExample: kit.ObjectExample,
	Expandable: kit.Expandable,
	EnumValues: kit.EnumValues,
	Enum: kit.Enum
} as unknown as Record<string, Component>;
